package app

var disclosureTypeGroups = []DisclosureGroupDTO{
	{
		GroupID:      "group-001",
		Name:         "Định kỳ",
		Description:  "Nghĩa vụ công bố theo chu kỳ.",
		Icon:         "Calendar",
		DisplayOrder: 1,
	},
	{
		GroupID:      "group-002",
		Name:         "Bất thường",
		Description:  "Nghĩa vụ công bố theo sự kiện phát sinh.",
		Icon:         "AlertCircle",
		DisplayOrder: 2,
	},
	{
		GroupID:      "group-006",
		Name:         "Tùy chỉnh doanh nghiệp",
		Description:  "Template nội bộ do doanh nghiệp cấu hình.",
		Icon:         "Settings",
		DisplayOrder: 3,
	},
}

var disclosureDisplayGroupSeed = []DisplayGroupDTO{
	{DisplayGroupCode: "display-governance", NameVI: "Quản trị, Tuân thủ, Rủi ro & Pháp lý", NameEN: "Governance, Compliance, Risk & Legal", Description: "Các nghĩa vụ liên quan đến quản trị doanh nghiệp, tuân thủ pháp luật, quản trị rủi ro, pháp lý và các thay đổi quan trọng trong cơ cấu quản trị.", Icon: "ShieldCheck", DisplayOrder: 1, IsActive: true, IsSystem: true},
	{DisplayGroupCode: "display-strategy", NameVI: "Chiến lược, Điều hành & Tình báo thị trường", NameEN: "Strategy, Executive Management & Market Intelligence", Description: "Các thông tin về định hướng chiến lược, hoạt động điều hành, quyết định quản lý và tín hiệu thị trường có ảnh hưởng đến doanh nghiệp.", Icon: "GitMerge", DisplayOrder: 2, IsActive: true, IsSystem: true},
	{DisplayGroupCode: "display-finance", NameVI: "Tài chính, Hiệu quả kinh doanh & Kiểm soát hiệu suất", NameEN: "Finance, Business Performance & Performance Control", Description: "Các báo cáo và chỉ số liên quan đến tài chính, kết quả kinh doanh, hiệu quả vận hành, kiểm toán và kiểm soát hiệu suất.", Icon: "BarChart2", DisplayOrder: 3, IsActive: true, IsSystem: true},
	{DisplayGroupCode: "display-operations", NameVI: "Vận hành, Quy trình, Dự án & Chuyển đổi", NameEN: "Operations, Process, Project & Change Management", Description: "Các thông tin về hoạt động vận hành, quy trình nội bộ, dự án trọng điểm, chương trình chuyển đổi và thay đổi vận hành.", Icon: "Settings", DisplayOrder: 4, IsActive: true, IsSystem: true},
	{DisplayGroupCode: "display-growth", NameVI: "Tăng trưởng, Marketing, Bán hàng & Khách hàng", NameEN: "Growth, Marketing, Sales & Customer Management", Description: "Các thông tin liên quan đến tăng trưởng, thị trường, hoạt động marketing, bán hàng và quản lý quan hệ khách hàng.", Icon: "TrendingUp", DisplayOrder: 5, IsActive: true, IsSystem: true},
	{DisplayGroupCode: "display-people", NameVI: "Con người, Tri thức, Công nghệ, Dữ liệu & AI", NameEN: "People, Knowledge, Technology, Data & AI", Description: "Các thông tin liên quan đến nhân sự, tri thức tổ chức, công nghệ, dữ liệu, AI và năng lực số của doanh nghiệp.", Icon: "Users", DisplayOrder: 6, IsActive: true, IsSystem: true},
	{DisplayGroupCode: "group-006", NameVI: "CBTT/Báo cáo tùy chỉnh", NameEN: "Custom Disclosure / Custom Report", Description: "Các loại CBTT/Báo cáo do doanh nghiệp tự định nghĩa ngoài danh mục mặc định của hệ thống, phục vụ nhu cầu quản trị và công bố riêng.", Icon: "Layers", DisplayOrder: 7, IsActive: true, IsSystem: true},
}

var disclosureTypeCatalog = []DisclosureTypeDTO{
	{
		TypeID:                "dt-periodic-financial",
		GroupID:               "group-001",
		DisplayGroupCode:      "display-finance",
		Name:                  "Báo cáo tài chính định kỳ",
		Category:              "Định kỳ",
		TemplateCategory:      TemplateCategoryPeriodic,
		DeadlineStrategy:      DeadlineStrategyFixedCycleDays,
		Description:           "Công bố báo cáo tài chính theo quý.",
		LegalBasis:            "Thông tư 96/2020/TT-BTC",
		Applicability:         "Doanh nghiệp niêm yết",
		ImplementationContent: "Tổng hợp dữ liệu và lập báo cáo tài chính quý.",
		ImplementationNotes:   "Kiểm tra số liệu trước khi nộp.",
		SpecialCases:          "Điều chỉnh khi có kiểm toán ngoại lệ.",
		ReportContent:         "Báo cáo tài chính quý + thuyết minh.",
		RequiredDocs:          "BCTC quý, biên bản phê duyệt.",
		DeadlineRule:          "Trong vòng 20 ngày kể từ khi kết thúc quý.",
		Periodicity:           PeriodicityQuarterly,
		ChannelsText:          "UBCKNN, Sở GDCK",
		Beneficiaries:         "Nhà đầu tư, cơ quan quản lý",
		ReceivingAuthorities:  "UBCKNN, HOSE/HNX",
		Format:                "PDF",
		LegalRisksText:        "Phạt chậm công bố theo quy định hiện hành.",
		GeneralInfo:           "Áp dụng mặc định cho tất cả công ty niêm yết.",
		Tags:                  []string{"Định kỳ", "Tài chính"},
	},
	{
		TypeID:                "dt-event-major-change",
		GroupID:               "group-002",
		DisplayGroupCode:      "display-governance",
		Name:                  "Công bố sự kiện bất thường",
		Category:              "Bất thường",
		TemplateCategory:      TemplateCategoryIrregular,
		DeadlineStrategy:      DeadlineStrategyEventHours,
		Description:           "Công bố khi phát sinh sự kiện quan trọng.",
		LegalBasis:            "Luật chứng khoán hiện hành",
		Applicability:         "Doanh nghiệp niêm yết",
		ImplementationContent: "Tạo cảnh báo và công bố theo sự kiện.",
		ImplementationNotes:   "Ghi nhận thời điểm phát sinh chính xác.",
		SpecialCases:          "Sự kiện có yếu tố bảo mật nội bộ.",
		ReportContent:         "Thông báo sự kiện và tài liệu đính kèm.",
		RequiredDocs:          "Thông báo sự kiện, tài liệu pháp lý liên quan.",
		DeadlineRule:          "Trong vòng 24 giờ kể từ khi phát sinh sự kiện.",
		Periodicity:           PeriodicityEventBased,
		ChannelsText:          "UBCKNN, Website công ty",
		Beneficiaries:         "Nhà đầu tư, cổ đông",
		ReceivingAuthorities:  "UBCKNN",
		Format:                "PDF",
		LegalRisksText:        "Rủi ro xử phạt nếu chậm hoặc sai nội dung công bố.",
		GeneralInfo:           "Deadline xác định theo thời điểm sự kiện.",
		Tags:                  []string{"Bất thường", "Sự kiện"},
	},
	{
		TypeID:                "dt-custom-obligation",
		GroupID:               "group-006",
		DisplayGroupCode:      "group-006",
		Name:                  "Template nghĩa vụ tùy chỉnh",
		Category:              "Tùy chỉnh",
		TemplateCategory:      TemplateCategoryCustom,
		DeadlineStrategy:      DeadlineStrategyConfigurable,
		Description:           "Template nội bộ cho nghĩa vụ đặc thù doanh nghiệp.",
		LegalBasis:            "Quy chế nội bộ doanh nghiệp",
		Applicability:         "Theo phân quyền nội bộ",
		ImplementationContent: "Thiết lập workflow và checklist tài liệu.",
		ImplementationNotes:   "Điều chỉnh theo chính sách nội bộ.",
		SpecialCases:          "Thay đổi quy trình theo phiên bản template.",
		ReportContent:         "Nội dung theo template nội bộ.",
		RequiredDocs:          "Checklist hồ sơ theo cấu hình template.",
		DeadlineRule:          "Theo cấu hình của admin.",
		Periodicity:           PeriodicityMonthly,
		ChannelsText:          "Nội bộ",
		Beneficiaries:         "Ban điều hành",
		ReceivingAuthorities:  "Nội bộ",
		Format:                "PDF",
		LegalRisksText:        "Rủi ro tuân thủ nội bộ nếu không thực hiện đúng quy trình.",
		GeneralInfo:           "Dùng cho nghĩa vụ nội bộ chưa có mẫu chuẩn ngoài thị trường.",
		Tags:                  []string{"Tùy chỉnh"},
	},
	{
		TypeID:                "dt-obligation-report",
		GroupID:               "group-001",
		DisplayGroupCode:      "display-operations",
		Name:                  "Báo cáo nghĩa vụ",
		Category:              "Định kỳ",
		TemplateCategory:      TemplateCategoryPeriodic,
		DeadlineStrategy:      DeadlineStrategyFixedCycleDays,
		Description:           "Mẫu báo cáo nghĩa vụ tuân thủ định kỳ theo yêu cầu quản trị.",
		LegalBasis:            "Quy chế công bố thông tin và tuân thủ nội bộ",
		Applicability:         "Đơn vị/phòng ban có nghĩa vụ báo cáo",
		ImplementationContent: "Tổng hợp tình trạng thực hiện nghĩa vụ và hành động khắc phục.",
		ImplementationNotes:   "Đối chiếu checklist nghĩa vụ trước khi trình duyệt.",
		SpecialCases:          "Nghĩa vụ phát sinh đột xuất được chuyển sang template bất thường.",
		ReportContent:         "Báo cáo tổng hợp tình trạng nghĩa vụ, các mục chưa hoàn thành và kế hoạch xử lý.",
		RequiredDocs:          "Checklist nghĩa vụ, biên bản rà soát nội bộ.",
		DeadlineRule:          "Trong vòng 05 ngày làm việc kể từ kỳ chốt báo cáo.",
		Periodicity:           PeriodicityMonthly,
		ChannelsText:          "Nội bộ, email quản trị",
		Beneficiaries:         "Ban điều hành, bộ phận kiểm soát",
		ReceivingAuthorities:  "Nội bộ",
		Format:                "PDF",
		LegalRisksText:        "Rủi ro vi phạm nội bộ và chậm xử lý nghĩa vụ.",
		GeneralInfo:           "Dùng cho các nghĩa vụ vận hành/tuân thủ cần theo dõi định kỳ.",
		Tags:                  []string{"Nghĩa vụ", "Định kỳ"},
	},
	{
		TypeID:                "dt-shareholder-meeting",
		GroupID:               "group-001",
		DisplayGroupCode:      "display-strategy",
		Name:                  "Tổ chức đại hội cổ đông",
		Category:              "Định kỳ",
		TemplateCategory:      TemplateCategoryPeriodic,
		DeadlineStrategy:      DeadlineStrategyFixedCycleDays,
		Description:           "Template điều phối công bố thông tin liên quan tổ chức đại hội cổ đông.",
		LegalBasis:            "Luật Doanh nghiệp và quy chế công bố thông tin hiện hành",
		Applicability:         "Doanh nghiệp cổ phần/niêm yết",
		ImplementationContent: "Lập kế hoạch, thông báo mời họp, công bố tài liệu đại hội theo timeline.",
		ImplementationNotes:   "Kiểm tra thời hạn chốt danh sách cổ đông và hạn công bố tài liệu.",
		SpecialCases:          "Đại hội bất thường theo nghị quyết đột xuất có thể dùng template bất thường bổ sung.",
		ReportContent:         "Thông báo mời họp, chương trình họp, tài liệu đại hội và nghị quyết.",
		RequiredDocs:          "Thông báo họp, tài liệu đại hội, danh sách cổ đông, biên bản và nghị quyết.",
		DeadlineRule:          "Ít nhất 21 ngày trước ngày họp (hoặc theo điều lệ/quy định áp dụng).",
		Periodicity:           PeriodicityYearly,
		ChannelsText:          "UBCKNN, Sở GDCK, Website công ty",
		Beneficiaries:         "Cổ đông, nhà đầu tư, cơ quan quản lý",
		ReceivingAuthorities:  "UBCKNN, HOSE/HNX",
		Format:                "PDF",
		LegalRisksText:        "Rủi ro khiếu kiện và xử phạt nếu công bố không đúng hạn hoặc thiếu hồ sơ.",
		GeneralInfo:           "Áp dụng cho kế hoạch và công bố thông tin Đại hội cổ đông thường niên.",
		Tags:                  []string{"Đại hội cổ đông", "Định kỳ"},
	},
	{
		TypeID:                "dt-disclosure-transaction",
		GroupID:               "group-002",
		DisplayGroupCode:      "display-finance",
		Name:                  "Công bố thông tin về giao dịch",
		Category:              "Bất thường",
		TemplateCategory:      TemplateCategoryIrregular,
		DeadlineStrategy:      DeadlineStrategyEventHours,
		Description:           "Template công bố thông tin khi phát sinh giao dịch thuộc diện phải công bố.",
		LegalBasis:            "Luật Chứng khoán và các quy định công bố giao dịch hiện hành",
		Applicability:         "Doanh nghiệp niêm yết và chủ thể liên quan giao dịch",
		ImplementationContent: "Tiếp nhận thông tin giao dịch, kiểm tra điều kiện công bố và phát hành thông báo.",
		ImplementationNotes:   "Ghi nhận chính xác thời điểm phát sinh giao dịch và thông tin chủ thể liên quan.",
		SpecialCases:          "Giao dịch có yếu tố bảo mật cần kiểm tra phạm vi công bố trước khi phát hành.",
		ReportContent:         "Thông tin giao dịch, giá trị, đối tượng liên quan và tài liệu xác nhận.",
		RequiredDocs:          "Thông báo giao dịch, tài liệu pháp lý/chứng từ liên quan.",
		DeadlineRule:          "Trong vòng 24 giờ kể từ khi phát sinh hoặc nhận được thông tin giao dịch thuộc diện công bố.",
		Periodicity:           PeriodicityEventBased,
		ChannelsText:          "UBCKNN, Sở GDCK, Website công ty",
		Beneficiaries:         "Nhà đầu tư, cổ đông, cơ quan quản lý",
		ReceivingAuthorities:  "UBCKNN, HOSE/HNX",
		Format:                "PDF",
		LegalRisksText:        "Rủi ro xử phạt và ảnh hưởng uy tín khi công bố sai/chậm.",
		GeneralInfo:           "Sử dụng cho các giao dịch phải công bố theo cơ chế bất thường.",
		Tags:                  []string{"Giao dịch", "Bất thường"},
	},
}

func SeedDisplayGroups() []DisplayGroupDTO {
	out := make([]DisplayGroupDTO, len(disclosureDisplayGroupSeed))
	copy(out, disclosureDisplayGroupSeed)
	return out
}

func SeedDisclosureTypeGroups() []DisclosureGroupDTO {
	out := make([]DisclosureGroupDTO, len(disclosureTypeGroups))
	copy(out, disclosureTypeGroups)
	return out
}

func SeedDisclosureTypeCatalog() []DisclosureTypeDTO {
	out := make([]DisclosureTypeDTO, len(disclosureTypeCatalog))
	copy(out, disclosureTypeCatalog)
	return out
}
