package app

import (
	"crypto/rand"
	"encoding/hex"
	"sync"
	"time"
)

// Sprint 3 / Batch 5 — Workflow Override Rebase Apply.
//
// previewCache is the minimal, ephemeral, in-process cache PREFLIGHT_AUDIT.md §2 documents
// adding: Batch 3/4 always returned preview_id=null (fully stateless); Batch 5's apply
// preconditions require a referenceable preview to check freshness against, so this batch closes
// that gap exactly the way IMPLEMENTATION_BATCH_PLAN.md's own text always anticipated — "at most
// a temporary server-side cache key... not a database row." No migration, no new table.
//
// Entries expire after previewCacheTTL; an expired or unknown preview_id at apply time is
// 410 PREVIEW_UNAVAILABLE / 409 PREVIEW_EXPIRED (never silently treated as still valid).

const previewCacheTTL = 15 * time.Minute

type previewCacheEntry struct {
	CompanyID       string
	TypeID          string
	BaseVersionNo   int
	TargetVersionNo int
	GeneratedAt     time.Time
}

type previewCache struct {
	mu      sync.Mutex
	entries map[string]previewCacheEntry
}

func newPreviewCache() *previewCache {
	return &previewCache{entries: map[string]previewCacheEntry{}}
}

func (c *previewCache) Put(companyID, typeID string, baseVersionNo, targetVersionNo int) string {
	id := mintPreviewID()
	c.mu.Lock()
	defer c.mu.Unlock()
	c.entries[id] = previewCacheEntry{
		CompanyID: companyID, TypeID: typeID,
		BaseVersionNo: baseVersionNo, TargetVersionNo: targetVersionNo,
		GeneratedAt: time.Now().UTC(),
	}
	return id
}

// Get returns (entry, found, expired). found=false means the id was never issued (or this
// process restarted since — a cold cache is treated identically to "not found", never as "valid
// by default"). expired=true means it WAS issued but has aged out.
func (c *previewCache) Get(id string) (previewCacheEntry, bool, bool) {
	c.mu.Lock()
	defer c.mu.Unlock()
	e, ok := c.entries[id]
	if !ok {
		return previewCacheEntry{}, false, false
	}
	if time.Since(e.GeneratedAt) > previewCacheTTL {
		delete(c.entries, id)
		return previewCacheEntry{}, true, true
	}
	return e, true, false
}

func mintPreviewID() string {
	buf := make([]byte, 16)
	_, _ = rand.Read(buf)
	return "prv_" + hex.EncodeToString(buf)
}

// globalPreviewCache is process-wide (mirrors roleRegistryForConflictDetection's own
// process-wide-singleton convention in workflow_override_conflict.go) — a preview generated by
// one request must be visible to a later apply request on the same process, which is the only
// guarantee this cache needs to provide (no cross-process/cross-restart durability is claimed or
// required — restart invalidates all outstanding previews, which is safe-by-default: an apply
// against an unknown preview_id is rejected, never silently accepted).
var globalPreviewCache = newPreviewCache()
