CREATE TABLE IF NOT EXISTS cms_media_assets (
  asset_id VARCHAR(64) NOT NULL PRIMARY KEY,
  company_id VARCHAR(64) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  content_type VARCHAR(128) NOT NULL,
  size_bytes BIGINT NOT NULL,
  context VARCHAR(64) NULL,
  object_key VARCHAR(512) NOT NULL,
  upload_method VARCHAR(8) NOT NULL DEFAULT 'PUT',
  state ENUM('pending_upload', 'ready', 'deleted') NOT NULL DEFAULT 'pending_upload',
  upload_expires_at DATETIME(3) NOT NULL,
  etag VARCHAR(128) NULL,
  checksum VARCHAR(128) NULL,
  created_by VARCHAR(64) NOT NULL,
  updated_by VARCHAR(64) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  completed_at DATETIME(3) NULL,
  deleted_at DATETIME(3) NULL,
  UNIQUE KEY uq_cms_media_object_key (object_key),
  KEY idx_cms_media_company_created (company_id, created_at),
  KEY idx_cms_media_company_state (company_id, state),
  KEY idx_cms_media_company_type (company_id, content_type)
);
