SET NAMES utf8mb4;
SELECT rc.REFERENCED_TABLE_NAME, rc.TABLE_NAME, rc.CONSTRAINT_NAME, rc.DELETE_RULE
FROM information_schema.REFERENTIAL_CONSTRAINTS rc
WHERE rc.CONSTRAINT_SCHEMA = 'cobo_iam'
  AND rc.REFERENCED_TABLE_NAME IN ('disclosure_types','disclosure_type_versions')
ORDER BY rc.REFERENCED_TABLE_NAME, rc.TABLE_NAME;

SELECT TABLE_NAME, COLUMN_NAME
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA='cobo_iam' AND COLUMN_NAME='type_id'
ORDER BY TABLE_NAME;

SELECT TABLE_NAME, COLUMN_NAME
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA='cobo_iam' AND COLUMN_NAME IN ('template_id','record_id')
ORDER BY TABLE_NAME, COLUMN_NAME;
